config/routes.rb
Rails.application.routes.draw do
  resources :manages do
    resources :tasks
  end

  # ... other routes ...

  root to: "manages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/manage.rb
class Manage < ApplicationRecord
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :manage

  validates :status, inclusion: { in: ['incomplete', 'ongoing', 'complete'] }

  STATUS_OPTIONS = [
    ['Incomplete', 'incomplete'],
    ['Ongoing', 'ongoing'],
    ['Complete', 'complete']
  ]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :manages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/manages_controller.rb
class ManagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_manage, only: %i[ show edit update destroy ]

  # GET /manages or /manages.json
  def index
    @manages = current_user.manages
  end

  # GET /manages/1 or /manages/1.json
  def show
    @task = @manage.tasks.build
  end

  # GET /manages/new
  def new
    @manage = current_user.manages.build
  end

  # GET /manages/1/edit
  def edit
  end

  # POST /manages or /manages.json
  def create
    @manage = current_user.manages.build(manage_params)

    respond_to do |format|
      if @manage.save
        format.html { redirect_to manage_url(@manage), notice: "Manage was successfully created." }
        format.json { render :show, status: :created, location: @manage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manages/1 or /manages/1.json
  def update
    respond_to do |format|
      if @manage.update(manage_params)
        format.html { redirect_to manage_url(@manage), notice: "Manage was successfully updated." }
        format.json { render :show, status: :ok, location: @manage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manages/1 or /manages/1.json
  def destroy
    @manage.destroy!

    respond_to do |format|
      format.html { redirect_to manages_url, notice: "Manage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_manage
    @manage = current_user.manages.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: "Manage record not found"
  end

  # Only allow a list of trusted parameters through.
  def manage_params
    params.require(:manage).permit(:name, :description, :status)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_manage
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET manages/1/tasks
  def index
    @tasks = @manage.tasks
  end

  # GET manages/1/tasks/1
  def show
  end

  # GET manages/1/tasks/new
  def new
    @task = @manage.tasks.build
  end

  # GET manages/1/tasks/1/edit
  def edit
  end

  # POST manages/1/tasks
  def create
    @task = @manage.tasks.build(task_params)

    if @task.save
      redirect_to(@task.manage)
    else
      render action: 'new'
    end
  end

  # PUT manages/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to(@task.manage, notice: 'Task was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE manages/1/tasks/1
  def destroy
    @task.destroy

    redirect_to manage_url(@manage)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manage
      @manage = current_user.manages.find(params[:manage_id])
    end

    def set_task
      @task = @manage.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :manage, :references)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manages_helper.rb
module ManagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #00ccff9d;">
      <div class="container">
        <!-- Navbar brand/logo -->
        <a class="navbar-brand" href="#">ManageApp</a>
        
      </div>
    </nav>

    <div class="container pt-5 pb-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="card">
        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/manages/_form.html.erb
<%= form_with(model: manage) do |form| %>
  <% if manage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(manage.errors.count, "error") %> prohibited this manage from being saved:</h2>

      <ul>
        <% manage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, rows: 5, cols: 40%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/manages/_manage.html.erb
<div id="<%= dom_id manage %>">
  <p>
    <strong>Name:</strong>
    <%= manage.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= manage.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= manage.user_id %>
  </p>

</div>

app/views/manages/edit.html.erb
<h1>Editing manage</h1>

<%= render "form", manage: @manage %>

<br>

<div>
  <%= link_to "Show this manage", @manage %> |
  <%= link_to "Back to manages", manages_path %>
</div>

app/views/manages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Manages</h1>

<div id="manages">
  <% @manages.each do |manage| %>
    <%= render manage %>
    <p>
      <%= link_to "Show this manage", manage %>
    </p>
  <% end %>
</div>

<%= link_to "New manage", new_manage_path %>

app/views/manages/new.html.erb
<h1>New manage</h1>

<%= render "form", manage: @manage %>

<br>

<div>
  <%= link_to "Back to manages", manages_path %>
</div>

app/views/manages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @manage %>

<div>
  <%= link_to "Edit this manage", edit_manage_path(@manage) %> |
  <%= link_to "Back to manages", manages_path %>

  <%= button_to "Destroy this manage", @manage, method: :delete %>
</div>
<hr>

<h1>New task</h1>

<%= render 'tasks/form' %>

<%= link_to 'Back', manage_tasks_path(@task.manage) %>

<hr>

<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Manage</th>
    <th>References</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @manage.tasks.each do |task| %>
<% if task.persisted? %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.manage %></td>
    <td><%= task.references %></td>
    <td><%= link_to 'Show', [task.manage, task] %></td>
    <td><%= link_to 'Edit', edit_manage_task_path(task.manage, task) %></td>
    <td><%= link_to 'Destroy', [task.manage, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_manage_task_path(@manage.id) %>

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.manage, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <br />
    <%= f.text_area :description, rows: 5, cols: 40 %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Task::STATUS_OPTIONS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', [@task.manage, @task] %> |
<%= link_to 'Back', manage_tasks_path(@task.manage) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Manage</th>
    <th>References</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.manage %></td>
    <td><%= task.references %></td>
    <td><%= link_to 'Show', [task.manage, task] %></td>
    <td><%= link_to 'Edit', edit_manage_task_path(task.manage, task) %></td>
    <td><%= link_to 'Destroy', [task.manage, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_manage_task_path(params[:manage_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', manage_tasks_path(@task.manage) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Manage:</b>
  <%= @task.manage %>
</p>

<p>
  <b>References:</b>
  <%= @task.references %>
</p>


<%= link_to 'Edit', edit_manage_task_path(@task.manage, @task) %> |
<%= link_to 'Back', manage_tasks_path(@task.manage) %>